# Generated by Django 3.1.2 on 2020-10-15 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zvitae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitae',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvitae',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvitae',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
