# Generated by Django 3.1.2 on 2020-10-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvitae', '0002_auto_20201015_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvitae',
            name='description',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvitae',
            name='title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
