# Generated by Django 3.1.2 on 2020-10-19 22:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zvitae', '0005_auto_20201016_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cvitae',
            new_name='Zvitae',
        ),
    ]
