# Generated by Django 3.1.2 on 2020-10-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zvitae', '0006_auto_20201020_0045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zvitae',
            table='zvitae',
        ),
    ]
