# Generated by Django 3.1.2 on 2020-11-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zvitae', '0007_auto_20201029_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postal_code', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CivilState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('linkedin', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('driving_licence', models.CharField(max_length=200, null=True)),
                ('address_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zvitae.address')),
                ('cvitae_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zvitae.zvitae')),
            ],
        ),
    ]
