# Generated by Django 3.1.2 on 2020-11-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zvitae', '0008_address_civilstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civilstate',
            old_name='cvitae_details',
            new_name='zvitae_link',
        ),
        migrations.RemoveField(
            model_name='civilstate',
            name='address_details',
        ),
        migrations.AddField(
            model_name='address',
            name='zvitae_link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zvitae.zvitae'),
            preserve_default=False,
        ),
    ]
