# Generated by Django 3.1.2 on 2020-11-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zvitae', '0009_auto_20201109_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zvitae_link',
            new_name='zvitae_link_add',
        ),
        migrations.RenameField(
            model_name='civilstate',
            old_name='zvitae_link',
            new_name='zvitae_link_cs',
        ),
    ]
